- name: Remove old WP_HOME and WP_SITEURL definitions
  lineinfile:
    path: /opt/bitnami/wordpress/wp-config.php
    regexp: "define\\( ?'WP_(HOME|SITEURL)', ?'[^']+' ?\\);"
    state: absent

- name: Add new WP_HOME and WP_SITEURL
  blockinfile:
    path: /opt/bitnami/wordpress/wp-config.php
    insertbefore: "define\\( 'WP_AUTO_UPDATE_CORE', 'minor' \\);"
    block: |
      define( 'WP_HOME', '{{ wp_home }}' );
      define( 'WP_SITEURL', '{{ wp_siteurl }}' );
  notify: Restart Apache
